# Generated by Django 2.2.2 on 2019-07-04 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190704_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 3, 24, 4, 813462, tzinfo=utc)),
        ),
    ]
