# Generated by Django 2.2.2 on 2019-08-08 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190704_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(choices=[('Tutorial', 'Tutorial'), ('Project', 'Project'), ('Dev Tip', 'Dev Tip')], default='Project', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 17, 54, 37, 890364, tzinfo=utc)),
        ),
    ]
