# Generated by Django 2.2.2 on 2019-08-09 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190808_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_picture', models.ImageField(upload_to='sitesettings/')),
                ('hero_background', models.ImageField(upload_to='')),
                ('default_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 4, 50, 14, 78053, tzinfo=utc)),
        ),
    ]
