# Generated by Django 2.2.2 on 2019-08-09 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190809_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 4, 50, 49, 727727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_image',
            field=models.ImageField(upload_to='sitesettings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(upload_to='sitesettings/'),
        ),
    ]
